added scss, lectures page
Team-Chicken-Nuggets/fydp-frontend pull request #5
Opened 2020-11-14 07:39 UTC by alexgirard

Basic UI for lectures page, more work needs to be done with the url hashing for course-specific lecture pages.
Also added a main scss file to include font and any site-wide styling

Notes:
- Header needs to be done
- Need to figure out how we're storing and retrieving assets

2020-11-14 17:47 UTC, BenLanglois requested changes

2020-11-14 17:47 UTC, BenLanglois commented on src/components/VideoCards.jsx
> +      <VideoCard key={lecture.title} {...lecture} />
Title might not be unique, so we probably shouldn't use it as a key. Maybe use an ID, since I'm pretty sure we'll have one for lectures.

2020-11-14 17:47 UTC, BenLanglois commented on src/util/time.js
> +    .reduce((prev, curr, i) => prev + curr * Math.pow(60, i), 0);
I think we should store video position/length as a number and convert it to a string when it needs to be displayed, rather than storing it as a string and parsing it to a number. That way we won't end up with a video with length NaN or something because of a parsing error.

2020-11-14 17:47 UTC, BenLanglois commented on src/pages/Lectures.jsx
> +    PropTypes.shape({
Can we import the lecture PropType from src/components/VideoCards.jsx?

2020-11-14 17:47 UTC, BenLanglois commented on src/pages/Lectures.jsx
> +Lectures.defaultProps = {
We should probably delete this and make everything required

2020-11-14 20:52 UTC, BenLanglois commented on src/components/VideoCards.jsx
> +    {lectures.reverse().map(lecture => (
`reverse` mutates the array, which probably isn't intended. Make a shallow copy first to avoid mutating the array.
```suggestion
    {[...lectures].reverse().map(lecture => (
```

2020-11-16 02:17 UTC, alexgirard commented on src/components/Checkmark.jsx
> +  background: #5637ad;
Yeah! in the main scss file we can create variables to use within the application

2020-11-16 02:18 UTC, alexgirard commented on src/components/Checkmark.jsx
> +const Checkmark = styled.span`
hmm sure? I've never used feather... generally I use with font awesome. Have you used it before?

2020-11-16 02:22 UTC, alexgirard commented on src/components/VideoCards.jsx
> +        <ProgressBar percent={percentageTime(position, length)} height={12} />
hmm yeah I agree I guess for this mvp we won't have a status stored, we should for the final implementation

2020-11-16 02:30 UTC, alexgirard commented on src/util/time.js
> +    .reduce((prev, curr, i) => prev + curr * Math.pow(60, i), 0);
removed util file => no longer storing status

2020-11-16 02:41 UTC, alexgirard commented
Updated! pls take another look

2020-11-16 02:42 UTC, alexgirard commented on src/pages/Lectures.jsx
> +Lectures.defaultProps = {
Keeping it now for data, will delete once hooked up to graphl

2020-11-16 02:55 UTC, BenLanglois approved these changes
🚀

2020-11-16 02:55 UTC, BenLanglois commented on src/components/Checkmark.jsx
> +const Checkmark = styled.span`
I've used feather icons before, it's pretty user friendly. I haven't used font-awesome before, but I would be OK with using that too.

2020-11-16 02:55 UTC, BenLanglois commented on src/components/Checkmark.jsx
> +export default Checkmark;
I don't think this is being used anymore, so the file can be deleted.

2020-11-16 03:16 UTC, alexgirard commented on src/components/Checkmark.jsx
> +export default Checkmark;
Whops sorry I thought I deleted it

2020-11-16 03:18 UTC, merged